apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-jtl-storage
  labels:
    app: {{ .Release.Name }}-jtl-storage

spec:
  accessModes:
    - ReadWriteMany

  storageClassName: {{ .Values.db.jtlPersistence.storageClassName | default "efs-sc" }}

  resources:
    requests:
      storage: {{ .Values.db.jtlPersistence.size | default "5Gi" }}