apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app: {{ .Release.Name }}-postgres

spec:
  serviceName: postgres
  replicas: 1

  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres

    spec:
      containers:
        - name: postgres
          image: postgres:18

          ports:
            - containerPort: 5432

          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-postgres-config

          volumeMounts:
            # EBS - Postgres DB data
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

            # EFS - JTL storage (your requirement)
            - name: jtl-storage
              mountPath: /app/jtl-storage
              subPath: backend/test_reports

  volumes:
    # EFS PVC (NOT in volumeClaimTemplates)
    - name: jtl-storage
      persistentVolumeClaim:
        claimName: {{ .Release.Name }}-jtl-storage

  volumeClaimTemplates:
    # EBS ONLY for Postgres
    - metadata:
        name: postgres-data
        labels:
          app: {{ .Release.Name }}-postgres
        annotations:
          "helm.sh/resource-policy": keep

      spec:
        accessModes:
          - {{ .Values.db.accessModes | default "ReadWriteOnce" }}

        storageClassName: {{ .Values.db.storageClassName | default "gp3" }}

        resources:
          requests:
            storage: {{ .Values.db.size | default "30Gi" }}