apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tenjin-pt-service
  labels:
    app: tenjin-pt-service
spec:
  type: {{ .Values.tenjin-pt-service.service.type | default "ClusterIP" }}
  selector:
    app: tenjin-pt-service
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.tenjin-pt-service.service.port | default 8080 }}       # Service port
      targetPort: 8080
