apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tenjin-pt-standalone
  labels:
    app: {{ .Release.Name }}-tenjin-pt-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-tenjin-pt-standalone
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-tenjin-pt-standalone
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              until nc -zv {{ .Release.Name }}-postgres 5432; do
                echo "Waiting for postgres to be available..."
                sleep 5
              done

      containers:
        - name: tenjin-pt-standalone
          image: "{{ .Values.tenjinStandalone.image | default "yethitech/tenjin-pt-standalone:2.2.0" }}"
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-tenjin-pt-standalone-config

          volumeMounts:
            - name: shared-storage
              mountPath: /root

      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-tenjin-shared-pvc